services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  ##############################################
  #   connect:                                 #
  #   - server: db (service name)              #
  #   - username: root                         #
  #   - password: 1234 (mysql_root_password)   #
  #   url phpmyadmin: localhost:port           #
  ##############################################
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql:

# docker-compose -f .\docker-compose.yml up